# Я художник, я так вижу, визуализация данных в питоне

# I. Numpy

### Импортируйте NumPy

In [3]:
# ВАШ КОД ЗДЕСЬ
import numpy as np

### Создайте одномерный массив размера 10, заполненный нулями и пятым элемент равным 1. Трансформируйте в двумерный массив.

In [14]:
# ВАШ КОД ЗДЕСЬ
arr_1d = np.zeros((10,), dtype=int)
arr_1d.put(5,1)
arr_2d = arr_1d.reshape(2,5)
print(f'arr_1d = {arr_1d}')
print(f'arr_2d = {arr_2d}')

arr_1d = [0 0 0 0 0 1 0 0 0 0]
arr_2d = [[0 0 0 0 0]
 [1 0 0 0 0]]


### Создайте одномерный массив со значениями от 10 до 49 и разверните его (первый элемент становится последним). Найдите в нем все четные элементы.

In [43]:
# ВАШ КОД ЗДЕСЬ
arr = np.arange(10, 50, dtype=int)
flipped_arr = np.flip(arr)
print(arr)
print(flipped_arr)

#1 способ
even_mask = flipped_arr % 2 == 0
even_arr = set(int(value) for value in flipped_arr[even_mask])
print(f'even_arr: {even_arr}')

#2 способ
even = set()
for value in flipped_arr:
    if value % 2 == 0:
        even.add(int(value))
print(f'even arr = {even}')

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
even_arr: {10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48}
even arr = {10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48}


### Создайте двумерный массив 3x3 со значениями от 0 до 8

In [27]:
# ВАШ КОД ЗДЕСЬ
arr = np.arange(0,9, dtype=int).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Создайте массив 4x3x2 со случайными значениями. Найти его минимум и максимум.

In [31]:
# ВАШ КОД ЗДЕСЬ
arr = np.random.randn(4, 3, 2)
print(arr)
min_val = arr.min()
max_val = arr.max()
print(min_val, max_val)

[[[ 1.38507362 -0.73713559]
  [ 0.07956441 -0.19516397]
  [ 1.55688425  1.11633046]]

 [[-0.4022084   2.0966573 ]
  [-0.44130588 -0.76256619]
  [ 0.62164251 -0.53312402]]

 [[ 0.36988914 -0.70692788]
  [-2.81413292 -2.43551054]
  [ 0.4201037   0.946563  ]]

 [[ 0.72123558  1.07774012]
  [-0.54703543  0.33902844]
  [ 0.2644891  -0.05499134]]]
-2.8141329230403196 2.096657301245623


### Создайте два двумерных массива размерами 6x4 и 4x3 и произведите их матричное умножение. 

In [35]:
# ВАШ КОД ЗДЕСЬ
random_array_6_4 = np.random.rand(6, 4)
random_array_4_3 = np.random.rand(4, 3)
print(random_array_6_4)
print(random_array_4_3)

res = random_array_6_4 @ random_array_4_3
print(res)


[[0.28352688 0.54184858 0.76693691 0.65052459]
 [0.90115245 0.91723331 0.2509339  0.83516847]
 [0.57549086 0.48046223 0.98607938 0.1105526 ]
 [0.25227306 0.53662392 0.80114886 0.31865308]
 [0.38307688 0.82067985 0.87260312 0.20285428]
 [0.52347954 0.09839139 0.24497568 0.86544779]]
[[0.05862482 0.81373419 0.60007125]
 [0.96551844 0.41129573 0.20494958]
 [0.38531236 0.55238544 0.49371244]
 [0.05480412 0.85473768 0.27852131]]
[[0.87094821 1.43324819 0.84101922]
 [1.08089418 1.9630149  1.08524366]
 [0.88364051 1.30509802 0.96143697]
 [0.85906581 1.1409021  0.74565149]
 [1.16218136 1.30466533 0.88538567]
 [0.26750986 1.341493   0.69628349]]


### Создайте случайный двумерный массив 7x7, найти у него среднее и стандартное оклонение. Нормализуйте этот массив.

In [47]:
# ВАШ КОД ЗДЕСЬ
arr = np.random.rand(7, 7)
print(arr)
mean = np.mean(arr)
std = np.std(arr)
print(mean, std)

#1 способ
normalized_arr_1 = (arr - mean) / std
print(f'normalized_arr_1: {normalized_arr_1}')

#2 способ
normalized_arr_2 = arr / np.linalg.norm(arr, axis=-1)[:, np.newaxis]
print(f'normalized_arr_1: {normalized_arr_2}')

[[0.11869322 0.0159681  0.95298677 0.28026232 0.06874417 0.92447901
  0.73315721]
 [0.73049098 0.07634629 0.75799288 0.80269579 0.74985922 0.86538023
  0.14548315]
 [0.05898913 0.61230922 0.12141437 0.68971931 0.65146527 0.40310585
  0.75489918]
 [0.96995997 0.62895767 0.14082769 0.09611571 0.3520371  0.24347277
  0.89849555]
 [0.65995958 0.38688144 0.07276735 0.85913644 0.32090801 0.60683745
  0.77941333]
 [0.34079149 0.98575588 0.35838172 0.18889631 0.85150848 0.43976388
  0.97134151]
 [0.04951542 0.1796378  0.1391508  0.02305799 0.05887616 0.0270678
  0.61164608]]
0.4644000619750884 0.32753762201777326
normalized_arr_1: [[-1.05547216 -1.36910062  1.49169645 -0.56218806 -1.20797083  1.40465985
   0.82053824]
 [ 0.81239803 -1.18476091  0.89636366  1.0328454   0.8715309   1.22422628
  -0.97368025]
 [-1.23775377  0.45157914 -1.04716426  0.68791868  0.57112585 -0.18713641
   0.88691833]
 [ 1.54351705  0.50240827 -0.98789377 -1.1244032  -0.3430536  -0.67450966
   1.32533015]
 [ 0.5970597 

# II. Pandas

### Импортируйте: pandas, matplotlib, seaborn

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Загрузите датасет Tips из набора датасетов seaborn

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Посмотрите на первые 5 строчек

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Узнайте сколько всего строчек и колонок в данных

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Проверьте есть ли пропуски в данных

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Посмотрите на распределение числовых признаков

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Найдите максимальное значение 'total_bill'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Найдите количество курящих людей

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Узнайте какой средний 'total_bill' в зависимости от 'day'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Отберите строчки с 'total_bill' больше медианы и узнайте какой средний 'tip' в зависимости от 'sex'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Преобразуйте признак 'smoker' в бинарный (0-No, 1-Yes)

In [ ]:
# ВАШ КОД ЗДЕСЬ

# III. Visualization

### Постройте гистограмму распределения признака 'total_bill'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте scatterplot, представляющий взаимосвязь между признаками 'total_bill' и 'tip'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте pairplot

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте график взаимосвязи между признаками 'total_bill' и 'day'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте две гистограммы распределения признака 'tip' в зависимости от категорий 'time'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте два графика scatterplot, представляющих взаимосвязь между признаками 'total_bill' и 'tip' один для Male, другой для Female и раскрасьте точки в зависимоти от признака 'smoker'

In [ ]:
# ВАШ КОД ЗДЕСЬ

## Сделайте выводы по анализу датасета и построенным графикам. По желанию можете продолжить анализ данных и также отразить это в выводах.

In [ ]:
# ВАШ КОД ЗДЕСЬ