# “Git push -f” или после нас хоть потоп

# 0. Где мы сейчас?
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png" width="150">

[Jupyter Notebook](https://jupyter.org/) - интерактивная среда для запуска программного кода в браузере. Удобный инструмент для анализа данных, который используется многими специалистами по data science. Позволяет выполнять отдельные ячейки с кодом, а не всю программу сразу, что очень удобно при знакомстве с данными.

# 1. Python
> Python - это свободный интерпретируемый объектно-ориентированный расширяемый встраиваемый язык программирования очень высокого уровня

>*(Г.Россум, Ф.Л.Дж.Дрейк, Д.С.Откидач "Язык программирования Python").*

А если без цитат, то питон - это просто очень крутой язык, созданный в 1991 году [Великодушным пожизненным диктатором](https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%B4%D1%83%D1%88%D0%BD%D1%8B%D0%B9_%D0%BF%D0%BE%D0%B6%D0%B8%D0%B7%D0%BD%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B4%D0%B8%D0%BA%D1%82%D0%B0%D1%82%D0%BE%D1%80) Гвидо ван Россумом и названный в честь любимого им шоу [Monty Python's Flying Circus](https://en.wikipedia.org/wiki/Monty_Python%27s_Flying_Circus)

<img src="https://advancelocal-adapter-image-uploads.s3.amazonaws.com/image.oregonlive.com/home/olive-media/width2048/img/tv/photo/2018/10/10/montycastjpg-7ef393e2355a42aa.jpg" width="300">

# 2. Anaconda

[Сборка Anaconda](https://www.anaconda.com/products/individual) включает очень много полезных библиотек для анализа данных.

Среди наиболее популярных библиотек:
 - <a href="http://numpy.org">Numpy</a> - это один из основных пакетов для математических вычислений. Он содержит средства для работы с многомерными массивами и высокоуровневыми математическими функциями
 - <a href="https://www.scipy.org/">SciPy</a> - научные вычисления. Методы оптимизации, интегрирования, модули обработки сигналов и изображений, статистика, линейная алгебра, сплайны, кластеризация и многое другое
 -  <a href="http://pandas.pydata.org/">Pandas</a> - основная библиотека для обработки и анализа данных. Предназначена для данных разной природы - матричных, панельных данных, временных рядов. Претендует на звание самого мощного и гибкого средства для анализа данных с открытым исходным кодом
 - <a href="http://scikit-learn.org/stable/">Scikit-learn</a> - реализация очень многих методов машинного обучения с отличной документацией.
 - <a href="http://http://matplotlib.org/">matplotlib</a> - хорошая библиотека для визуализации данных

 С этими библиотеками вы будете знакомится дальше на курсе, а пока давайте попрактикуемся в решении базовых задач на  чистом Python.

# 3. Задачки

## Задача 1
$N$ хоббитов делят $K$ кусков эльфийского хлеба поровну, не делящийся нацело остаток остается в корзинке у Сэма. Напишите функцию, которая принимает на вход параметры $N$ и $K$ и возвращает два числа: $x$ - cколько кусков эльфиского хлеба достанется каждому хоббиту, и $y$ - сколько кусков остаётся в корзинке.

In [1]:
def share_bread(N, K):
    # your code here
    x = K // N
    y = K % N
    return x, y

# если в функции всё верно, то после выполнения этой строчки, не должно выскакивать ошибок
assert share_bread(N=3, K=14) == (4, 2)

## Задача 2

В копях Мории хоббиты нашли стену, на которой высечены разные натуральные числа. Согласно древним сказаниям, это даты сражений. Хоббиты знают, что сражения происходили только по високосным годам. Помогите хоббитам определить, является ли год с данным числом датой великого сражения. Если это так, то верните строку "YOU SHALL PASS", иначе верните "YOU SHALL NOT PASS". Напомним, что в соответствии с хоббитским календарем, год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.

In [3]:
def leap_year(year):
    # your code here
    text_result = ''
    if year % 4 == 0 and year % 100 != 0 and year % 400 == 0:
        text_result = 'YOU SHALL PASS'
    else:
        text_result = 'YOU SHALL NOT PASS'

    return text_result

assert leap_year(5) == 'YOU SHALL NOT PASS'

## Задача 3
<img src="http://i0.kym-cdn.com/photos/images/original/001/187/255/5e9.gif" width=300>


Для могущественного магического ритуала Гендальфу необходимо быстро подсчитывать площадь своего амулета, который умеет менять размеры. Известно, что амулет имеет форму треугольника и Гендальф знает длину каждой из сторон. Напишите функцию, которая считает площадь амулета по трем сторонам.  

**Подсказка:** используйте формулу Герона
$$ S = \sqrt{p(p-a)(p-b)(p-c)} $$
$$ p = \frac{a + b + c}{2}$$


In [4]:
def amulet_area(a, b, c):
    # your code here
    p = (a + b + c) / 2
    S = (p * (p - a) * (p - b) * (p - c)) ** 0.5
    return S

assert amulet_area(3, 4, 5) == 6

## Задача 4

Хоббиты собираются пешком идти до Мордора и им нужно подсчитать расстояние, которое им предстоит пройти. Хоббиты смогли вспомнить сразу несколько метрик расстояния: евклидово, манхэттена и косинусное, так что ваша задача - написать функцию под каждую из них. Важное условие - используйте только базовые функции для решения.


* Евклидово расстояние
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Расстояние Манхэттена
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Косинусное расстояние
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2}$$

In [33]:
def cal_euclidean(a, b):
    ## Your code here
    sum_elem = 0
    for elem_a, elem_b in zip(a, b):
        sum_elem += pow(elem_a - elem_b,2)
    distance = sum_elem ** 0.5
    return distance

def cal_manhattan(a, b):
    ## Your code here
    distance = 0
    for elem_a, elem_b in zip(a, b):
        distance += abs(elem_a - elem_b,)
    return distance


def calc_norm(a):
    norm = 0
    for elem_a in a:
        norm += elem_a ** 2
    return norm ** 0.5

def cal_cosine(a, b):
    ## Your code here
    scalar_mult = 1
    for elem_a, elem_b in zip(a, b):
        scalar_mult += elem_a * elem_b
    norm_a = calc_norm(a)
    norm_b = calc_norm(b)
    distance = 1 - scalar_mult / (norm_a * norm_b)
    return distance


In [52]:
import numpy as np
a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)

print(cal_euclidean(a, b))
print(cal_manhattan(a, b))
print(cal_cosine(a, b))

34.08812109811862
100
1.6970994433492597


## Задача 5* (бонусное неоцениваемое задание)

**Замечание:** Поскольку библиотеку numpy мы будем подробно разбирать дальше, то это задание является бонусным, его выполнение необязательно для сдачи ДЗ и не влияет на итоговый балл. Как вариант, можете вернуться к нему после прохождения numpy ;)



Создайте случайный array (`np.random.rand()`) длинной 100. Преобразуйте его так, чтобы
* Максимальный элемент(ы) был равен 1
* Минимальный элемент(ы) был равен 0
* Остальные элементы в интервале от 0 до 1 остаются прежними

In [2]:
my_array = ## Your code here
print(np.max(my_array), np.min(my_array))
print(my_array)

0.9994206039810671 0.02396791845377677
[0.41896137 0.0422874  0.66117033 0.2154423  0.13879252 0.14594596
 0.59267787 0.547053   0.89295063 0.07335426 0.25231303 0.45012032
 0.98040802 0.94402705 0.09849127 0.25011245 0.07321031 0.19726815
 0.65902832 0.60022019 0.4487886  0.57336417 0.32843971 0.38789236
 0.08307283 0.34153187 0.28177155 0.11419758 0.50822736 0.40669383
 0.21499707 0.51538512 0.44204371 0.57057954 0.66387032 0.07752299
 0.95689922 0.766288   0.16579714 0.79093544 0.64375204 0.48688714
 0.068985   0.483213   0.93120168 0.40192935 0.75143005 0.42180394
 0.53584315 0.27532823 0.57162423 0.21745628 0.90390974 0.89286852
 0.76379932 0.64436442 0.83887789 0.25511191 0.55534981 0.59981849
 0.27885905 0.9994206  0.80446336 0.64529979 0.09052195 0.17851431
 0.77394983 0.03552978 0.96098737 0.96776653 0.53676908 0.08110662
 0.47476568 0.58259963 0.83660406 0.87862468 0.74232494 0.82849198
 0.55429918 0.81521675 0.62730151 0.38394737 0.2682892  0.90373108
 0.50444753 0.55835126 

Создайте array размером $5 \times 6$ с целыми числами в интервале [0,50]. Напечатайте колонку, которая содержит максимальный элемент полученной матрицы

In [4]:
my_array = ## Your code here
selected_column = ## Your code here
print('Shape: ',my_array.shape)
print('Array')
print(my_array)
print(selected_column)

[[39  4 21 18  2 41]
 [ 6 29 20 22 24 18]
 [20  9 25 12 15 19]
 [45 47 44 26 46 49]
 [10 44 24 17 43 42]]


Напишите функцию, которая принимает на вход матрицу (array) X и возвращает все её уникальные строки в виде новой матрицы.

In [ ]:
def get_unique_rows(X):
    # Your code here
    return X_unique

In [3]:
X = np.random.randint(4, 6, size=(10,3))
print(X)

[[4 5 4]
 [5 5 5]
 [4 5 5]
 [5 5 4]
 [4 4 4]
 [5 5 5]
 [4 5 5]
 [5 4 5]
 [5 5 5]
 [4 4 4]]


In [ ]:
get_unique_rows(X)